import {
    AnnexIndex,
    ArticleIndex,
    ConsiderationToShow,
    RecitalToShow,
} from "@repo/resolution-assembly/definitions/resolutions";
import {DistributiveOmit} from "@/parser/types";

// --- Constants ---
export const MAX_CONTEXT_LENGTH = 800;
export const MAX_MAIN_TEXT_LENGTH = 2500;
export const OVERLAP = 500;

export type ChunkToEmbed = {
    mainText: string,
    contextText: string
}

export type ArticleLocation = {
    articleIndex: ArticleIndex
    chapterNumber: number | null
    annexIndex: AnnexIndex | null
}

export type DataToEmbed = {
    type: "RECITAL",
    number: number,
    chunks: ChunkToEmbed[]
} | {
    type: "CONSIDERATION",
    number: number,
    chunks: ChunkToEmbed[]
} | {
    type: "ARTICLE",
    location: ArticleLocation,
    chunks: ChunkToEmbed[]
} | {
    type: "TEXT_ANNEX",
    annexIndex: AnnexIndex,
    chunks: ChunkToEmbed[]
}

export type ReferenceTargetKey = string; // Generated by stableStringify of the target location

export type IndexedBlock =
    | { type: "RECITAL", data: RecitalToShow }
    | { type: "CONSIDERATION", data: ConsiderationToShow };



export type ChunkWithEmbedding = ChunkToEmbed & {
    embedding: number[]
}

export type DataWithEmbeddings = DistributiveOmit<DataToEmbed, "chunks"> & {
    chunks: ChunkWithEmbedding[]
}